#!/usr/bin/env python3
"""Generate skill index and example docs from one metadata table."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

CATALOG_PATH = ROOT / "references" / "skill-catalog.json"
CORE_METHODS_PATH = ROOT / "references" / "core-methods.json"


def load_catalog() -> dict:
    with CATALOG_PATH.open("r", encoding="ascii") as handle:
        catalog = json.load(handle)
    if not isinstance(catalog, dict) or not isinstance(catalog.get("skills"), list):
        raise ValueError(f"{CATALOG_PATH} must contain a skills list")
    return catalog


CATALOG = load_catalog()
SKILLS = CATALOG["skills"]
CORE_METHODS = json.loads(CORE_METHODS_PATH.read_text(encoding="ascii"))


def table(headers: list[str], rows: list[list[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def skill_link(name: str) -> str:
    return f"`{name}`"


def render_skill_index() -> str:
    inventory_rows = [
        [skill_link(item["name"]), item["does"], item["when"]]
        for item in SKILLS
    ]
    compat_rows = [
        [skill_link(item["name"]), item["artifact"], item["writes"], item["safe"]]
        for item in SKILLS
    ]
    workflow_rows = [
        [skill_link(item["name"]), item["does"]]
        for item in SKILLS
        if item["kind"] == "workflow"
    ]
    return "\n\n".join(
        [
            "# Skill Index",
            "Generated by `scripts/build_index.py` from `references/skill-catalog.json`.",
            "## Inventory",
            table(["Skill", "What it does", "Use when"], inventory_rows),
            "## Workflow Skills",
            table(["Workflow skill", "What it adds"], workflow_rows),
            "## Compatibility Quick Scan",
            table(["Skill", "Output artifact", "Writes files?", "Safe default?"], compat_rows),
        ]
    ) + "\n"


def render_all_examples() -> str:
    rows = [
        [skill_link(item["name"]), f"`{item['prompt']}`", item["output"]]
        for item in SKILLS
    ]
    return "\n\n".join(
        [
            "# All Skills Example Index",
            "Generated by `scripts/build_index.py` from `references/skill-catalog.json`.",
            "Use this file as a quick product tour. Each row gives a concrete prompt shape and the expected output artifact.",
            table(["Skill", "Example prompt", "Expected output"], rows),
            "## Close The Loop Example",
            "```text\nUse x-review-pack on this launch plan.\nApprove x-compound only if a reusable lesson is worth saving.\nUse x-handoff only if another session needs to continue the work.\n```",
            "Expected result: a bounded review that produces a decision, approved memory only when useful, and a compact continuation artifact only when needed.",
        ]
    ) + "\n"


def render_core_methods() -> str:
    rows = [
        [str(item["id"]), item["concept"], skill_link(item["skill"])]
        for item in CORE_METHODS["methods"]
    ]
    return "\n\n".join(
        [
            "# Core Methods Coverage",
            "Generated by `scripts/build_index.py` from `references/core-methods.json`.",
            "The wording is paraphrased and intentionally compact. This is a coverage map, not a quote archive or replacement for the source book.",
            table(["#", "Paraphrased method", "Runtime skill"], rows),
            "## Broader Book Coverage",
            "`x-multiplanetary` is book-derived from the main chapters but has no separate item in the 69-method bonus summary. Its broader mapping remains in `references/book-map.md`.",
        ]
    ) + "\n"


def render_skill_example(item: dict[str, str]) -> str:
    return "\n\n".join(
        [
            f"# {item['name']} Example",
            "Generated by `scripts/build_index.py` from `references/skill-catalog.json`.",
            "## Prompt",
            f"```text\n{item['prompt']}\n```",
            "## Expected Output",
            item["output"],
            "## Use When",
            item["when"],
            "## Write Behavior",
            item["writes"],
        ]
    ) + "\n"


def generated_files() -> dict[Path, str]:
    files: dict[Path, str] = {
        ROOT / "docs" / "SKILL_INDEX.md": render_skill_index(),
        ROOT / "examples" / "all-skills.md": render_all_examples(),
        ROOT / "references" / "CORE_METHODS.md": render_core_methods(),
    }
    for item in SKILLS:
        files[ROOT / "examples" / f"{item['name']}.md"] = render_skill_example(item)
    return files


def write_files() -> None:
    for path, text in generated_files().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="ascii")


def check_files() -> int:
    mismatches = []
    for path, expected in generated_files().items():
        actual = path.read_text(encoding="ascii") if path.exists() else None
        if actual != expected:
            mismatches.append(path.relative_to(ROOT).as_posix())
    if mismatches:
        print("generated files are stale:")
        for rel in mismatches:
            print(f"  {rel}")
        print("run: python3 scripts/build_index.py")
        return 1
    print("generated index files are current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate skill index and examples")
    parser.add_argument("--check", action="store_true", help="Fail when generated files are stale")
    args = parser.parse_args()
    if args.check:
        return check_files()
    write_files()
    print(f"generated {len(generated_files())} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
